describe('runtime error', () => {
  it('throws a error', () => {
    throw new Error('error thrown on purpose')
  })
})
